# config/params.yaml
custom_joy_teleop: # 우리가 런치 파일에서 지정한 노드의 'name'
  ros__parameters: # (고정) 이 아래에 파라미터들을 나열합니다.
    initial_max_linear_vel: 0.6
    initial_max_angular_vel: 1.2
    linear_step: 0.1
    angular_step: 0.2
    alpha_linear: 0.1
    alpha_angular: 0.3
    deadzone: 0.05